### ISSUE TITLE
How to create a grpc endpoint without DI .

### ISSUE THREAD

**Issue by bklooste** [grpc/grpc-dotnet#1358] opened 2021-07-29 08:19 UTC
Is there anyway to create grpc endpoint in a light manner without all the heavy DI and a dedicated service with base class eg more like the new .NET 6 stuff and Go.

    app.MapGet("/", async context => ..
    app.MapGet("/",  () => "Hello World!");
    app.MapGet("/todos", async (DbContext db) => await db.ToListAsync() );

**Comment by JamesNK** [comment] 2021-07-29 08:30
Not at the moment. gRPC uses generated service types which makes this model difficult.

**Comment by JamesNK** [comment] 2021-08-04 08:55
Duplicate of https://github.com/grpc/grpc-dotnet/issues/111

**Closed by JamesNK** 2021-08-04 08:55 UTC
Labels: question
