### ISSUE TITLE
Grpc.Net.Client.Web fails with "Bad gRPC response. Response protocol downgraded to HTTP/1.1."

### ISSUE THREAD

**Issue by phirivie** [grpc/grpc-dotnet#813] opened 2020-03-08 14:30 UTC
### What version of gRPC and what language are you using?
Grpc.Net.Client.Web 2.28.0-pre1 , C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core 3.1.101

### What did you do?
updated Grpc.Net.Client.Web from 2.27.0-pre1 to 2.28.0-pre1

### What did you expect to see?
continue using a working grpc authorized channel

### What did you see instead?
Following exception occurred when using authorized channels for grpc clients:
"Bad gRPC response. Response protocol downgraded to HTTP/1.1."

I reverted back to version 2.27.0-pre1 and it works again so something is going wrong in the next version 2.28.0-pre1

Other info: I use Blazor webassembly with the experimental gRPC client package v2.27.0-pre1 for using gRPC so maybe the added functionality does not come in further releases?

**Comment by mateusz-pietrzak** [comment] 2020-03-08 22:25
Same for me. Had to revert to 2.27.0-pre1.

**Comment by JamesNK** [comment] 2020-03-08 22:54
Duplicate of https://github.com/grpc/grpc-dotnet/issues/805

**Closed by JamesNK** 2020-03-08 22:54 UTC
Labels: bug
