### ISSUE TITLE
How to properly share message definitions between micro-services and Map from database to message defintion?

### ISSUE THREAD

**Issue by JohnGalt1717** [grpc/grpc-dotnet#978] opened 2020-07-10 18:26 UTC
I think this is a pretty standard use case:

Microservice A
      Proto1.proto (referencing User.prot)
Microservice B
       Proto2.proto (referencing User.proto)
Shared Messages
        User.proto
        Automapper or similar Profile mapping

Share a few messages.

Use automapper or equivalent to map the results as responses without having to create multiple profiles.

But no matter what I do, I can't figure out how to make proto files fully aware of other messages in other protos that are shared between projects which I think would be a basic (i.e. a User Message would almost certainly be shared)

In a perfect world, I'd have all of my message dtos in a project and then have the other protos reference these with their types and namespaces sticking without including them in the Microservice dll so it would know the cshapr_namespace and just reference it but not include the files thus Automapper would know what to do with them because they'd be the same and we wouldn't have to repeat ourselves.

**Comment by JunTaoLuo** [comment] 2020-07-22 20:06
Closing this as duplicate of https://github.com/grpc/grpc-dotnet/issues/988 since we responded there and added a sample.

**Closed by JunTaoLuo** 2020-07-22 20:06 UTC
Labels: question
