### ISSUE TITLE
405 no-referrer-when-downgrade, disallowed verb?

### ISSUE THREAD

**Issue by ThatRickGuy** [grpc/grpc-dotnet#884] opened 2020-04-25 18:40 UTC
I'm seeing a 405 error in my network traffic when trying to call the gRPC service. It looks like the gRPC-Web client is sending a POST but the server is only allowing GET. 
```
Request URL: https://MyDomain.com/Class.Collection/GetCollection
**Request Method: POST**
Status Code: 405 
Remote Address: 64.209.142.58:443
Referrer Policy: no-referrer-when-downgrade
**allow: GET, HEAD, OPTIONS, TRACE**
```

I'm getting a bit more info from the Console output, but I'm not sure if the 405 is causing this error, or this error is causing the 405. Any pointers?

`Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")`

**Comment by JamesNK** [comment] 2020-04-25 21:23
> 405

Is the gRPC-Web request cross-domain? Is CORS setup to allow gRPC-Web? See https://github.com/grpc/grpc-dotnet/tree/master/examples#spar for an example of gRPC-Web + CORS.

> Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

Are you using the latest version of Grpc.Net.Client.Web?

**Comment by ThatRickGuy** [comment] 2020-04-26 01:26
GRPC.Net.Client.Web is 2.28.0-pre2

Blazor (client side) and gRPC services are both hosted on the same domain, in a sub folder (thanks to your recommendation here https://github.com/grpc/grpc-dotnet/issues/880 )

**Comment by JamesNK** [comment] 2020-04-26 02:45
Is the scheme different? e.g. web page is http and the gRPC-Web call is https.

What are you doing on the server to have a sub folder?

Can you upload source code of a simple reproduction?

**Comment by ThatRickGuy** [comment] 2020-04-26 05:48
At this point, I think I've managed to bork my deployment configuration up. I just managed to get a 500.21 error. I'm going to see about getting the stripped down sample running tomorrow.

**Comment by shirhatti** [comment] 2020-04-27 21:10
Can you share an sample repo that produces this issue? Can you also share an IIS FREB log for the failing request?

**Comment by JamesNK** [comment] 2020-05-13 20:03
Closing because there is no feedback.

**Closed by JamesNK** 2020-05-13 20:03 UTC
Labels: needs-author-feedback, question
