### ISSUE TITLE
Grpc Under Load Problem

### ISSUE THREAD

**Issue by melfeqy** [grpc/grpc-dotnet#1516] opened 2021-12-03 16:17 UTC
Hi ,

I'm using grpc client streaming with .Net 5 and i need to handle 1000 simultaneous request and each request should take 50 milliseconds.

currently when i send 1000 simultaneous request it took 9 seconds to be handled and each request takes about 7 seconds(average).

Machine specs

- Windows Server 2019
- 32 GB RAM
- 16 Core

Channel Configuration

```C#
  var channel = GrpcChannel.ForAddress(ServiceUrl, new GrpcChannelOptions
            {
                HttpHandler = new SocketsHttpHandler
                {
                    EnableMultipleHttp2Connections = true,
                    MaxConnectionsPerServer = 1000
                }
            });

Kestrel Configuration


webBuilder.ConfigureKestrel((context, options) =>
                {
                    var port = context.Configuration.GetSection("HostPort").Get<int>();
                    options.ListenAnyIP(port, o => o.Protocols = HttpProtocols.Http2);
                    options.Limits.Http2.MaxStreamsPerConnection = 1000;
                });
```

**Comment by adityamandaleeka** [comment] 2021-12-06 21:16
@melfeqy Can you try again without setting `options.Limits.Http2.MaxStreamsPerConnection`? Having that many streams per connection will cause you to experience a lot of contention given your simultaneous requests.

**Comment by melfeqy** [comment] 2021-12-07 11:08
> @melfeqy Can you try again without setting `options.Limits.Http2.MaxStreamsPerConnection`? Setting this value will send all requests on one connection which can hurt performance. Having that many streams per connection will cause you to experience a lot of contention given your simultaneous requests.
> 
> If performance is still bad then we'll need a reproduction of the problem to be able to help further.
 

I tried to set options.Limits.Http2.MaxStreamsPerConnection to 200 and also100 and no difference also tried to use unary and the problem still exist.

the only thing decrease latency when i made client load balancer, i made 10 instances on same machine but still can't reach the 1000 request per second  with max latency 50ms and also measurements after load balancer not stable a lot of spikes for each try

**Comment by rafikiassumani-msft** [comment] 2021-12-07 22:18
@melfeqy Can you provide a reproduction that allows us to observe the problem ?

**Comment by melfeqy** [comment] 2021-12-09 14:55
> @melfeqy Can you provide a reproduction that allows us to observe the problem ?
![system-flow](https://user-images.githubusercontent.com/88893189/145416121-a05ed913-565a-48db-a4aa-75b19bfd94b5.png)

Please find the attached diagram that clear our system flow

**Notes**
1- we have only one fix connection per client  and market so if there is another client there will be another service Like service 1 and if there any another market there will be another service like service 3 and these are not scalable 
2- Business service has our logic and responsible for redirect to  specific market 
3- When receive orders from client we open new thread using **Task.Run()**
4- I was using grpc client streaming but found unary under load is better 
5- Our target is order time to market to be less than 50 ms(entry in service 1 to exit from service 3 ) under load
6- We actually achieve the target of 50 ms without load.
7- We have high machine specs( 16 Core - 32 GB RAM - Windows Server) and we can increase it
8-Cpu is totally consumed when send 1000 simultaneous orders
 
Thanks

**Comment by JamesNK** [comment] 2021-12-09 19:22
> When receive orders from client we open new thread using Task.Run()

Are you blocking on the task from `Task.Run()`? If you are blocking and not awaiting then your app is likely using up all the available threads.

**Comment by melfeqy** [comment] 2021-12-09 19:59
> > When receive orders from client we open new thread using Task.Run()
> 
> Are you blocking on the task from `Task.Run()`? If you are blocking and not awaiting then your app is likely using up all the available threads.

`session.InboundApplicationMessage += InboundApplicationMessageRecived; //receiving message event

       private void InboundApplicationMessage(object sender, InboundMessageEventArgs e) // event handler
        {
            Task.Run(() => SendMessage(e.Message));
        }

       private async void SendMessage(Message message)
        {
             await _cache.GetStringAsync(message.originalOrderId);
             await _cache.SetAsync("key","value");
             await grpcClient.SendMessage(message);            
        }`

**Notes**

i was working on machine with 8 core and cpu totally consumed i upgraded it to 16 cores also cpu totally consumed
but i expected at least latency will decrease when upgrade to more cores but 
unfortunately nothing happened only a very little decrease.

But when i make a client load balancer in **service 1** and make 10 instance from **service 2** on the same machine
specs latency starts to decrease

**Comment by JamesNK** [comment] 2021-12-11 18:37
Task.Run isn't doing anything for you there. Also, any errors in SendMessage will never be reported because you're using async void.

I don't know what your problem is.

**Comment by davidfowl** [comment] 2021-12-11 19:31
@melfeqy I'd recommend using [dotnet counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters) to get some top level metrics about your applications' behavior.

**Comment by melfeqy** [comment] 2021-12-11 19:36
> Task.Run isn't doing anything for you there. Also, any errors in SendMessage will never be reported because you're using async void.
> 
> I don't know what your problem is.

Thanks

**Comment by rafikiassumani-msft** [comment] 2021-12-20 21:09
@melfeqy We will close this issue as we believe we have provided enough guidance to help resolve your problem.

**Closed by rafikiassumani-msft** 2021-12-20 21:09 UTC
Labels: question, needs-author-feedback
