### ISSUE TITLE
RpcException causes "Infinite recursion during resource lookup within System.Private.CoreLib." and terminates process

### ISSUE THREAD

**Issue by invidious9000** [grpc/grpc-dotnet#1193] opened 2021-02-06 07:16 UTC
### What version of gRPC and what language are you using?
C# net5.0
Grpc.Net.Client 2.34.0

### What operating system (Linux, Windows,...) and version?
Win 10 x64 - 10.0.19041

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
5.0.102

### What did you do?

Made an AsyncUnary client call and awaited the response headers and then response, the server immediately writes response headers and then after a short delay intentionally throws an RpcException.
```cs
        static async Task Main()
        {
            using var channel = GrpcChannel.ForAddress("http://localhost:5001");
            var client =  new Greeter.GreeterClient(channel);
            var helloCall =  client.SayHelloAsync(new HelloRequest { Name = "GreeterClient" });
            Console.WriteLine(string.Join(", ", await helloCall.ResponseHeadersAsync));
            Console.WriteLine(await helloCall.ResponseAsync);
        }
```

### What did you expect to see?
An RpcException thrown while awaiting response.

### What did you see instead?
Response headers are printed and then the process terminates when it should be throwing RpcException.
```
[Entry: key=date, value=Sat, 06 Feb 2021 06:59:37 GMT], [Entry: key=server, value=Kestrel]
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Exception_EndOfInnerExceptionStack
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.SR.GetResourceString(System.String)
   at System.SR.get_Exception_EndOfInnerExceptionStack()
   at System.Exception.ToString()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyProject.Program.<Main>(System.String[])
```

When running this under Rider it suggests the following:
`
Target process has exited during evaluation of instance method System.Exception.ToString() with actual parameters Grpc.Core.RpcException. This may possibly happen due to StackOverflowException.`

**Comment by JamesNK** [comment] 2021-02-06 08:06
Hi

That's an interesting error. I've never seen it before. Could you also copy and past the server gRPC method code into this issue?

**Comment by invidious9000** [comment] 2021-02-06 09:05
Hello,
It terminates client application maybe 1/10 calls with thin greeter example using slightly modified ASP gRPC template; in my actual application code it's closer to 8/10 calls - perhaps there's a timing aspect? 

I narrowed it down further and eliminated the response header write on server side and it still produces that error. There's a dummy interceptor that _seems_ to make it occur more frequently but this could just be a perception issue.

[GreeterException.zip](https://github.com/grpc/grpc-dotnet/files/5936536/GreeterException.zip)

I am running under Debug/AnyCPU.


```cs
    public class GreeterService : Greeter.GreeterBase
    {
        public override async Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            await Task.Delay(TimeSpan.FromSeconds(4));
            throw new SomeException("Bad Stuff");
        }
    }

    public class SomeException : Exception
    {
        public SomeException()
        {
        }

        public SomeException(string? message) : base(message)
        {
        }
    }
```

**Comment by invidious9000** [comment] 2021-02-06 09:15
Not sure if this helps but Grpc.AspNetCore.Server.ClientFactory does not appear to exhibit the error for me at all.

**Comment by invidious9000** [comment] 2021-02-08 17:11
@JamesNK After a couple days of playing with it I think I've narrowed it down a bit further, with actual application code 100% of first calls to that server result in infinite recursion error. Subsequent calls produce RpcException as expected. This also applies to the Greeter example I posted, testing only first-calls increased frequency enough to reliably screencap the behavior.

![2021-02-08_10h05_12](https://user-images.githubusercontent.com/11744292/107255680-cfd9e600-69f5-11eb-8d7b-f59e8cd328b3.gif)

**Comment by tarekgh** [comment] 2021-02-08 23:01
@invidious9000 are you able to reproduce this problem if running on other machine? I have some suspicions could be something wrong in the running environment.

**Comment by tarekgh** [comment] 2021-02-09 01:29
Just to tell, I tried running the exact code you attached and I couldn't reproduce. 

One thing you can try is run your code from the command line (outside Visual Studio) and look if this will make any difference. You can use `dotnet build` to build and `dotnet run` to run the server and then run the client.

**Comment by invidious9000** [comment] 2021-02-09 03:34
@tarekgh I've tried to replicate on another Windows machine but have not yet been successful, it was difficult to catch the timing as it was.

I think I have replicated on Ubuntu.
![image](https://user-images.githubusercontent.com/11744292/107312041-cc257e00-6a4c-11eb-82d6-2cafb7a6f2f0.png)


For now I have switched to C-core Grpc client nuget (or ClientFactory for my ASP projects), neither of these exhibits the error.

**Comment by invidious9000** [comment] 2021-02-09 04:31
@tarekgh FWIW this seems to "fix" the error in Greeter sample as well as my actual application, is it possible this is a CoreCLR issue? ie. "This may be a bug in System.Private.CoreLib"

https://stackoverflow.com/a/48885319

![image](https://user-images.githubusercontent.com/11744292/107315897-d0ee3000-6a54-11eb-95fe-e0211838735f.png)

**Comment by tarekgh** [comment] 2021-02-09 04:53
> is it possible this is a CoreCLR issue? 

To answer that we'll need to get a repo to know what could be causing that. You mentioned you were able to reproduce the error on Ubuntu. do you have more details we can try? we are interested to know what is going on here. The original stack pasted above looks not complete too. is that the whole stack you saw or it is somehow truncated? Also, what is default culture in your machines that repro the issue?

@jkotas do you have any thoughts what could be going on here? I think the workaround is just changing the timing which made it to work but I am not sure as I don't have a repro to look at.

**Comment by jkotas** [comment] 2021-02-09 05:20
We would need to a crash dump to diagnose this crash. Could you please collect crash dump using instructions at https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps#collecting-dumps-on-crash and share it with us?

**Comment by invidious9000** [comment] 2021-02-09 05:37
Hello, I have a minidump for Windows and crash log from Ubuntu - both files are compressed but still > 10MB and cannot be posted to GitHub. How would you like these to be sent?

**Comment by invidious9000** [comment] 2021-02-09 05:47
Both dumps are attached as zips in 5MB chunks to work around GitHub file limit. File extension changed from .00X to .zip to get past extension filter, to make these valid archives again you must delete the last ".zip" in filename.

![image](https://user-images.githubusercontent.com/11744292/107321241-6a224400-6a5f-11eb-9cde-2d5c5bd86074.png)


Windows full minidump:

[dump.27316.zip.001.zip](https://github.com/grpc/grpc-dotnet/files/5949126/dump.27316.zip.001.zip)
[dump.27316.zip.002.zip](https://github.com/grpc/grpc-dotnet/files/5949127/dump.27316.zip.002.zip)
[dump.27316.zip.003.zip](https://github.com/grpc/grpc-dotnet/files/5949128/dump.27316.zip.003.zip)
[dump.27316.zip.004.zip](https://github.com/grpc/grpc-dotnet/files/5949130/dump.27316.zip.004.zip)
[dump.27316.zip.005.zip](https://github.com/grpc/grpc-dotnet/files/5949131/dump.27316.zip.005.zip)
[dump.27316.zip.006.zip](https://github.com/grpc/grpc-dotnet/files/5949135/dump.27316.zip.006.zip)
[dump.27316.zip.007.zip](https://github.com/grpc/grpc-dotnet/files/5949136/dump.27316.zip.007.zip)
[dump.27316.zip.008.zip](https://github.com/grpc/grpc-dotnet/files/5949138/dump.27316.zip.008.zip)

Ubuntu .crash file from /var/crash/
[_usr_share_dotnet_dotnet.1000.zip.001.zip](https://github.com/grpc/grpc-dotnet/files/5949164/_usr_share_dotnet_dotnet.1000.zip.001.zip)
[_usr_share_dotnet_dotnet.1000.zip.002.zip](https://github.com/grpc/grpc-dotnet/files/5949165/_usr_share_dotnet_dotnet.1000.zip.002.zip)
[_usr_share_dotnet_dotnet.1000.zip.003.zip](https://github.com/grpc/grpc-dotnet/files/5949166/_usr_share_dotnet_dotnet.1000.zip.003.zip)
[_usr_share_dotnet_dotnet.1000.zip.004.zip](https://github.com/grpc/grpc-dotnet/files/5949167/_usr_share_dotnet_dotnet.1000.zip.004.zip)
[_usr_share_dotnet_dotnet.1000.zip.005.zip](https://github.com/grpc/grpc-dotnet/files/5949168/_usr_share_dotnet_dotnet.1000.zip.005.zip)
[_usr_share_dotnet_dotnet.1000.zip.006.zip](https://github.com/grpc/grpc-dotnet/files/5949169/_usr_share_dotnet_dotnet.1000.zip.006.zip)

**Comment by jkotas** [comment] 2021-02-09 06:34
The dump shows a combinations of multiple aborted debugger funcevals and unhandled exceptions. Func eval is what is used to evaluate expressions in the debugger "Watch Window". You either have some bad expression in your "Watch Window" or it is a bug in the debugger.

Are you able to reproduce the crash when running without the Rider debugger attached?

**Comment by invidious9000** [comment] 2021-02-09 06:55
Thank you @jkotas and @tarekgh

I have no watches defined; I have not yet been able to reproduce without a debugger attached but even with Rider debugger attached it has been difficult to reproduce with Greeter example. I will try to reproduce without debugger and in VS, but I think I need to file an issue with Rider.

**Comment by JamesNK** [comment] 2021-02-10 19:47
Yes, this looks like a problem with the Rider debugger. Create an issue with JetBrains about this.

Thanks for providing so much information. Closing this issue as there is no work here for grpc-dotnet.

**Closed by JamesNK** 2021-02-10 19:47 UTC
Labels: bug

**Comment by alexrosenfeld10** [comment] 2021-03-03 12:22
FWIW, I have the same exact problem with a library I am working on. We also cannot replicate in any environment other than Rider, debugging in Visual Studio seems to evaluate all the properties on the object that causes this just fine.

If you might share the bug report number to Rider, I will open my own and reference it for more encouragement for their team to fix this problem.

**Comment by alexrosenfeld10** [comment] 2021-03-03 14:36
found it, looks like it's https://youtrack.jetbrains.com/issue/RIDER-57804
