### ISSUE TITLE
Unexpected OpenTelemetry tracing behavior when client doesn't have tracing configured

### ISSUE THREAD

**Issue by joaofbantunes** [grpc/grpc-dotnet#2427] opened 2024-05-05 11:16 UTC
Given the following scenario: two .NET microservices, one implementing a gRPC server, the other invoking it.

If we have OpenTelemetry fully setup on the server, but not on the client (either at all, or partially, i.e. `AddAspNetCoreInstrumentation` and `AddHttpClientInstrumentation`, but no `AddGrpcClientInstrumentation`), causes traces to not be exported on the server.

From what I could understand, when otel is not setup on the client service (or if `AddGrpcClientInstrumentation` isn't used and there's no existing parent trace), the `traceparent` header is still included, but the sampled flag is set to false, causing the server to ignore the traces (with the default configuration, we can force it using an `AlwaysOnSampler`).

At least to me this feels unexpected, as we might be creating a client service without even thinking about OpenTelemetry, but we're having an impact on the tracing behavior of the downstream service.

Also, from what I could observe, when doing "traditional" HTTP requests, with no otel setup on the client (or simply without using `AddHttpClientInstrumentation`), the `traceparent` header isn't included, so the downstream service decides how to handle things on its side.

Not sure correctly, but I was expecting something more like:

- If OpenTelemetry isn't configured at all in the client service, then it just doesn't send anything when making gRPC calls
  - Maybe it could forward an existing trace id if it existed, but even then it seems weird, if the service doesn't "know" about otel, probably shouldn't do anything related to it
- If OpenTelemetry is configured, but `AddGrpcClientInstrumentation` isn't used, fallback to the typical `HttpClient` behavior, as if the gRPC client wasn't part of the picture (which, from a tracing configuration perspective, it isn't)

Not sure this is a bug or by design, so creating the issue as a question. Is this by design?

**Comment by martinjt** [comment] 2024-05-05 23:02
This is because in the .NET Runtime, they've decided that Activity MUST be enabled (i.e. `Activity.Current `must exist) in order to correlate logs.

So if the logging is enabled for `Microsoft.AspNetCore.Hosting.Diagnostics` then an Activity is created for every request, and therefore `Activity.Current` is not null. Therefore anything in .NET that does propagation is now says "There's an Activity.Current, so I must propagate it".

The downstream applications know no different, they get a `traceparent` and continue propagation.

Here's a minimal repo: https://github.com/martinjt/dotnet-tracing-problem

Unfortunately, it's a runtime problem, and it's working as designed by Microsoft so the changes of getting that changed are almost non-existent.

@davidfowl Here's another manifestation of the issue we discussed on twitter.

I would advise closing this issue as it can't be fixed by gRPC .NET.

**Closed** 2024-05-05 23:03 UTC
Labels: question

**Comment by joaofbantunes** [comment] 2024-05-06 08:16
Thanks for the explanation @martinjt!
