### ISSUE TITLE
Add to gRPC benchmark environment

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#267] opened 2019-05-25 00:17 UTC
Setup new gRPC server in gRPC benchmark environment

https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584&widget=490377658&container=1286539696

**Comment by JunTaoLuo** [comment] 2019-06-10 23:05
Hey @jtattermusch can you help us with this issue?

**Comment by jtattermusch** [comment] 2019-06-11 13:42
I can set this up, but the current performance dashboard needs some improvements so I'm not sure if I'll be able to add this before some refactoring of the benchmarking environment is done.

**Comment by rafikiassumani-msft** [comment] 2022-01-25 00:20
Closing as a dupe of https://github.com/grpc/grpc-dotnet/issues/1395

**Closed by rafikiassumani-msft** 2022-01-25 00:20 UTC
