### ISSUE TITLE
Returning null from a grpc interceptor when there is a failure status code

### ISSUE THREAD

**Issue by ziaulhasanhamim** [grpc/grpc-dotnet#1555] opened 2022-01-06 03:58 UTC
Why can't return null from an interceptor there is a failure status code.
```c#
public class TestInterceptor : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        if (Some Logic)
        {
            return await  continuation(request, context);
        }
        context.Status = new Status(StatusCode.Unavailable, "Some information about the issue");
        return null!;
    }
}
```

I don't think I'm supposed to return a response when there is a failure status code. Or do I? When I return null with failure status code  I get this error message 
```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="No message returned from method.")
at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
```

**Comment by chwarr** [comment] 2022-01-10 17:21
Throw a [RpcException](https://grpc.github.io/grpc/csharp/api/Grpc.Core.RpcException.html) to terminate a call with an error from within an interceptor.

**Comment by ziaulhasanhamim** [comment] 2022-01-11 15:25
> Throw a [RpcException](https://grpc.github.io/grpc/csharp/api/Grpc.Core.RpcException.html) to terminate a call with an error from within an interceptor. With the current APIs, you have to throw an exception. There is no non-exceptional way to terminate a call from within an interceptor.

What is the motivation for [this block of code](https://github.com/grpc/grpc-dotnet/blob/518a6362ba5f03fb3169f22cc23fcae0b6471af6/src/Grpc.AspNetCore.Server/Internal/CallHandlers/UnaryServerCallHandler.cs#L52)?
```c#
if (response == null)
{
     // This is consistent with Grpc.Core when a null value is returned
     throw new RpcException(new Status(StatusCode.Cancelled, "No message returned from method."));
}
```
Afaik it's not always the case that there will be a response. There can be no response if something went wrong. That doesn't mean the request was Cancelled. I might have set appropriate status code and error messages using ServerCallContext.

**Comment by JamesNK** [comment] 2022-01-12 04:01
As the comment mentions, it is to be consistent with Grpc.Core.

Either a response should be returned, or an RpcException should be thrown. Returning a null response is not supported.

**Comment by ziaulhasanhamim** [comment] 2022-01-12 04:09
Is it only to be consistent with Grpc.Core? because I cant make sense of using StatusCode.Cancelled when nothing is returned from a rpc call.

**Comment by JamesNK** [comment] 2022-01-12 22:53
Yes

**Comment by JamesNK** [comment] 2022-01-20 01:15
And what about the code below it that then writes the message? It will error because response is null.

If you want to return a status then throw `RpcException`. That's how Grpc.Core and Grpc.AspNetCore.Server both work. Adding more ways of doing the same thing isn't a good argument unless there is a reason.

**Comment by ziaulhasanhamim** [comment] 2022-01-20 04:03
I think there is a reason. Most of the time one of the reasons for using grpc over rest is performance. Exceptions are not really the performant way because it breaks the normal code flow. Yeah, the performance difference for the exceptions is most of the time is unnoticeable and negligible. But what about other times? Also, exceptions can make code harder to read because of its nature of breaking the flow. For these reasons you can really see that the usage of exceptions is really been reduced from Asp.Net to Asp.Net Core. You want to throw an exception when something really went wrong in your application(not in the request).

**Comment by JamesNK** [comment] 2022-01-20 04:46
> Yeah, the performance difference for the exceptions is most of the time is unnoticeable and negligible. But what about other times?

gRPC doesn't use exceptions in typical application flow. If an HTTP request is being canceled, causing gRPC to throw a RpcException, an exception being thrown will have no impact at all on performance.

**Comment by ziaulhasanhamim** [comment] 2022-01-22 03:10
yea

**Comment by JamesNK** [comment] 2022-01-27 22:35
@jtattermusch Do you have any thoughts about this? Should a unary method be allowed to set the status on the ServerCallContext, return null, and have the status be sent in the response to the client?

**Comment by mayuki** [comment] 2022-03-03 04:00
We use MessagePack for `Marshaller` instead of protobuf, so it is possible to serialize `null` (`Nil`).
This means that a Unary method implementation that returns `null` as `TResponse` in `Method<TRequest, TResponse>` can still send a message body.

However, as discussed here, Grpc.AspNetCore.Server will block if it receives `null`.😢

**Comment by ziaulhasanhamim** [comment] 2022-03-03 04:37
> Grpc.AspNetCore.Server will block if it receives null

It can be changed. or can't?

**Comment by jtattermusch** [comment] 2022-04-05 07:42
> We use MessagePack for `Marshaller` instead of protobuf, so it is possible to serialize `null`. This means that a Unary method implementation that returns `null` as `TResponse` in `Method<TRequest, TResponse>` can still send a message body.
> 
> However, as discussed here, Grpc.AspNetCore.Server will block if it receives `null`.😢

I think that's a different issue from what's being discussed here though. Generally, we didn't allow messages to be be `null` since IIRC internally in Grpc.Core, a "null" message is used to signal that there will be no more request/responses in the request / response stream, so supporting "null" messages is a tricky proposition and would require additional work and testing (and we'd want Grpc.Core to stay consistent with grpc-dotnet in terms of what's supported).

**Comment by jtattermusch** [comment] 2022-04-05 07:55
So I don't think there's much value in supporting  `return null!` from the handler (regardless whether it's from an interceptor or a regular server side handler), when your intent is to return an error status code.
As suggested earlier, you can just as easily do this:
```
public class TestInterceptor : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        if (Some Logic)
        {
            return await  continuation(request, context);
        }
       throw new RpcException(new Status(StatusCode.Unavailable, "Some information about the issue"));
    }
}
```

This will do exactly what you need and it won't require returning what's otherwise and illegal return value (null message).

The argument about performance doesn't apply here since throwing and catching an exception has completely negligible overhead compared to starting/handling an RPC. I'd very surprised if you saw any noticeable difference in a benchmark.
And even if the performance mattered, you could simply specialize the interceptor to do

```
context.Status = new Status(StatusCode.Unavailable, "Some information about the issue");
return MyHelper.PreallocatedEmptyMessageOfTheResponseType;
```
(and if you're inside a regular server side handler, returning a default instance of a message as a dummy response is even simpler).

The problem with allowing `null` messages is orthogonal to this issue, as explained above.

I suggest closing this issue as it doesn't really limit the usability.

**Comment by JamesNK** [comment] 2022-04-05 08:47
Closing as I don't think the cost of this change is worth any potential benefit. Additionally, the workaround Jan mentioned, to return an empty dummy object, is available.

We'd need to see real-world scenarios where this exception has a noticeable impact on performance to consider this further.

**Closed by JamesNK** 2022-04-05 08:47 UTC
Labels: question

**Comment by hayohayo** [comment] 2025-07-30 23:01
I've been checking various related issues and this seems to be the closest to what I wanted to request. #1764 is close in spirit, but I'd like to comment on the server side.

The only proper way today to return a non-OK status code is by throwing an `RpcException`. I load tested my service on Linux, and under the same load service throwing exceptions used ~40% more CPU than using the "set status and return a dummy object" workaround.

That was a test, but there are other cases when our services throw:

- Reporting something regular, like `INVALID_ARGUMENT` or `NOT_FOUND`. There are much less of these than `OK`s, but still.
- We've built a rate-limiter for cases, when service is overloaded. And because we throw exceptions to reject incoming requests, service gets even more overloaded than if it just handled requests. That's very counter-intuitive.

I've checked the exception thrown counter and compared it with the number of requests. The ratio of exceptions to failed requests in one case was 13 to 1. And I guess these are just the same exceptions rethrown many times. Probably scales with the number of interceptors. I haven't measured the impact of having more interceptors.

For the workaround, first of all it looks like something unsupported. I need to test this and convince others that it is "supposed to work". Then status is really easy to set, the problem is the response. Application knows what the type is and can cache it, interceptor - does not. There's no `new()` constraint on the `TResponse`, so a generic way to create that response in the interceptor is via reflection and then cache it. But what happens if some interceptor mutates this shared object?.. I suppose it'll still be sent in the response body. Maybe?

Not throwing exceptions helps a lot! And it'd be great to not having to jump through the hoops here. `null` response (I think, it makes sense, actually) or a built-in factory for empty response (plus some guarantee that response will be ignored) are very welcome.
