### ISSUE TITLE
 Client gRPC won't work anymore after updating to 3.23.1 (works in 3.23.0) 

### ISSUE THREAD

**Issue by robertodalmonte** [grpc/grpc-dotnet#2135] opened 2023-05-18 08:40 UTC
### What version of gRPC and what language are you using?
c#, Google.Protobuf 3.23.1

### What operating system (Linux, Windows,...) and version?
Edition	Windows 11 Pro
Version	22H2
Installed on	‎28/‎09/‎2022
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.Net 7.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

This morning I updated my WPF project from:
Google.Protobuf 3.23.0 to Google.Protobuf 3.23.1
This is the only change I made.
I published my project using my usual settings:

    Configuration Release
    Platform Any CPU
    PublishProtocol FileSystem
    _TargetId Folder
    TargetFramework net7.0-windows
    RuntimeIdentifier win-x64
    SelfContained false
    PublishSingleFile true
    PublishReadyToRun true

If I try to launch my WPF client it stops as soon as trying to connect to my gRPC server.
I tried catching an error and logging it with Serilog, but I was not able to find it.

It does not happen if I run the project from Visual Studio in debug or if I launch the exe from the release folder after building (the difference here is that the libraries are not merged in one huge exe, as in publishing (I use PublishSingleFile = true).
I rolled back to 3.23.0
and I can publish my WPF project successfully and connect as usual to my gRPC Server app.
### What did you expect to see?
Being able to connect to my gRPC Server App from my gRPC Client App.

### What did you see instead?
The published (single file) client app is unable to connect to the gRPC Server.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
The gRPC Server App has been updated to 3.23.1 as well, and it works perfectly. I'm able as well to connect from my client gRPC app if I run it from Visual Studio, or if I launch the exe after building it in release. 
Any chance it might be related to the latest changes or should I look somewhere else?
Regards
Roberto

**Comment by JamesNK** [comment] 2023-05-18 09:14
I updated to 3.23.1, and all the tests still pass - https://github.com/grpc/grpc-dotnet/pull/2136

An error message or more information is needed.

**Comment by robertodalmonte** [comment] 2023-05-20 09:03
I was able to create a small solution that shows the problem. Please find it in the following Github repository
https://github.com/robertodalmonte/SolutionProtobuf
If you need it, I can send you my strong key to a private email address.
Regards

**Comment by JamesNK** [comment] 2023-05-24 00:53
I tested your solution when published as a single file, and it worked for me.

I added some more output to the logs. Output:

```
2023-05-24 08:48:05.079 +08:00 [INF] CheckServerAsync
2023-05-24 08:48:05.094 +08:00 [INF] Sending gRPC request
2023-05-24 08:48:05.105 +08:00 [INF] Created channel with address http://localhost:5087
2023-05-24 08:48:05.132 +08:00 [INF] OnStartup
2023-05-24 08:48:07.254 +08:00 [INF] Response { "IsUpToDate": true }
```

![image](https://github.com/grpc/grpc-dotnet/assets/303201/3e0bdec8-63ea-47f1-bb0c-7889d7680d10)

![image](https://github.com/grpc/grpc-dotnet/assets/303201/2dc0dab5-33bf-4301-9de7-701660d506ec)

**Comment by robertodalmonte** [comment] 2023-05-24 05:58
Hi James,
would you try the following settings:
![Screenshot (363)](https://github.com/grpc/grpc-dotnet/assets/24954850/539fb8ad-f19d-41b3-b9ba-7e113e8d6629)

I still have the problem, but since I updated Visual Studio 2022 to version 17.6.1 now things got worse:
while I can run successfully (using your settings in publishing the client app, as I did before) 
If I use my usual settings (please see image), it does not work with either version of Google.Protobuf (3.23.0 / 3.23.1)
So my take now is that the problem is not Google.Protobuf, but Publishing (I've had this problem already, which I solved by changing settings and giving up the "Single File" option).

**Comment by robertodalmonte** [comment] 2023-05-24 07:11
As a quick and confounding update, my main project still has problems only with 3.23.1.
If I publish it with 3.23.0 it works like a charm, with all my usual publishing settings.
Lost in the open sea

**Comment by JamesNK** [comment] 2023-05-25 03:35
I tried "Framework-dependent" and I did see the app fail to start. I made some changes in the app, and then I found it launched successfully and used Google.Protobuf 3.23.1 without error.

Honestly, I don't know what is going on. My guess is something about how the app is published as one file could cause an error. The crash is being recorded in the windows event log. When a crash happens there are dumps that you can look at.

**Comment by robertodalmonte** [comment] 2023-05-25 05:22
It's somewhat comforting that I'm not drunk:)
I found the error log, but I don't have the expertise to make sense of it: it looks Aramaic to me.
Who would be best to report this kind of error?

Log Name:      Application
Source:        Application Error
Date:          24/05/2023 08:53:34
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          BELVACODE\rober
Computer:      BelvaCode
Description:
Faulting application name: OneClick.Dental.exe, version: 0.7.0.0, time stamp: 0x641de100
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1635, time stamp: 0x61869dd2
Exception code: 0xe0434352
Fault offset: 0x000000000006536c
Faulting process id: 0x0x1964
Faulting application start time: 0x0x1D98E0C750D17A3
Faulting application path: D:\Github\OneClick\OneClick.Dental\bin\publish\OneClick.Dental.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5d15881b-d296-47ae-b124-360bb952a85a
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-05-24T06:53:34.5908162Z" />
    <EventRecordID>59494</EventRecordID>
    <Correlation />
    <Execution ProcessID="21828" ThreadID="29016" />
    <Channel>Application</Channel>
    <Computer>BelvaCode</Computer>
    <Security UserID="S-1-5-21-2822480387-2803349259-1076594727-1001" />
  </System>
  <EventData>
    <Data Name="AppName">OneClick.Dental.exe</Data>
    <Data Name="AppVersion">0.7.0.0</Data>
    <Data Name="AppTimeStamp">641de100</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.1635</Data>
    <Data Name="ModuleTimeStamp">61869dd2</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">000000000006536c</Data>
    <Data Name="ProcessId">0x1964</Data>
    <Data Name="ProcessCreationTime">0x1d98e0c750d17a3</Data>
    <Data Name="AppPath">D:\Github\OneClick\OneClick.Dental\bin\publish\OneClick.Dental.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">5d15881b-d296-47ae-b124-360bb952a85a</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by JamesNK** [comment] 2023-05-25 05:35
I don't have insight here either.

Like I said, I think the problem is caused by how the WPF app is published as a single file. Something about the IL in this version of Google.Protobuf, combined with your app, causes an error. I don't think it is a bug in Google.Protobuf or Grpc.Net.Client.

**Comment by JamesNK** [comment] 2023-06-01 01:46
Closing because I don't think there are any changes in grpc-dotnet.

**Closed by JamesNK** 2023-06-01 01:46 UTC
Labels: bug

**Comment by robertodalmonte** [comment] 2023-06-05 05:40
Hi James,
today I updated my main project from 
<PackageReference Include="Google.Protobuf" Version="3.23.0" />
to 
<PackageReference Include="Google.Protobuf" Version="3.23.2" />
I published my WPF client app and everything works perfectly.
Best Regards

**Comment by robertodalmonte** [comment] 2023-06-05 05:40
from Google.Protobuf 3.23.0 to 3.23.2

**Comment by robertodalmonte** [comment] 2023-08-09 10:11
Hi James,
just to let you know that today I upgraded from Google.Protobuf 3.23.4 to 3.24.0 and my app fails to start (after publishing).
So I restored 3.23.4 and everything works again.
I guess I'll skip this update
Regards
Roberto

**Comment by robertodalmonte** [comment] 2024-12-05 11:08
Hi James,
just to let you know that today I upgraded from Google.Protobuf 3.29.0 to 3.29.1 and my app fails to start (after single-file publishing).
So I restored 3.29.0 and everything works again.

Regards
Roberto
