### ISSUE TITLE
Streams sporadically throw unexpected exceptions

### ISSUE THREAD

**Issue by Schaeri** [grpc/grpc-dotnet#2122] opened 2023-05-11 11:37 UTC
In our testing, we have found that when using GRPC streams, the expected exceptions are not being delivered to the client. This occurs sporadically and very infrequently.  

The following attached code example demonstrates the problem with a simple console application. The program can be run either via VS, Rider, run.bat or dotnet run. 

[GrpcServiceStreamExceptionIssue.zip](https://github.com/grpc/grpc-dotnet/files/11451622/GrpcServiceStreamExceptionIssue.zip)

What does the example do:

- Starts a GRPC service
- Creates a client
- And calls in a loop a method that receives a GRPC stream
- This service method throws an exception with the status code 'PreConditionFailed'.
- If an error other than the expected one is found, the program stops execution and writes the result to the console.

To reproduce the error I need 20000 to 400000 loops. So the example runs for some time until the error occurs. 

Instead of the expected exception the following error occurs: IncompleteSendRpcException with the following message A message could not be sent because the server had already terminated the connection.
The example then gives the following output:

`Start GRPC Service
Wait until service is ready
Start test: Try to get wrong exception
Wrong exception found
Expected: (StatusCode FailedPrecondition + Detail TEST)
Found exception: IncompleteSendRpcException A message could not be sent because the server had already terminated the connection; this exception can be suppressed by specifying the IgnoreStreamTermination flag when creating the
CallContext
Number of test runs: 117211
Stop service`

Version Infos:

- protobuf-net.Grpc 1.1.1
- protobuf-net.Grpc.AspNetCore 1.1.1 
- Grpc.Net.Client 2.53.0
- .Net SDK 7.0.203
- Test System Windows 11 sowie Windows Server 2016

**Comment by JamesNK** [comment] 2023-06-15 22:47
The message says the connection is unexpectedly closed. Are you gracefully closing the gRPC stream? I have seen errors where streams aren't gracefully closed on the client and server, leading to a bad state that causes the server to abort the connection.

See https://learn.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-7.0#bi-directional-streaming-call

**Comment by Schaeri** [comment] 2023-06-16 09:15
An example project demonstrates the problem. In the service method nothing more is done than throwing an exception.  

`
public Task RunAsync(IAsyncEnumerable<TestRequest> request, CallContext context)
{
      throw new RpcException(new(StatusCode.FailedPrecondition, "TEST"));
} 
`

The problem occurs only sporadically after many attempts.

**Comment by JamesNK** [comment] 2023-06-21 12:52
On the server, you are throwing an exception and ending the request before reading the incoming content. That means the client can get a notification that the request is over:
1. Before it starts writing content. It doesn't try to write a message.
2. After it has finished writing content. The message is written successfully.
3. While it is writing content. You get this error.

Maybe the problem is in the protobuf-net client. I don't know, I'm not familiar with it.

**Closed** 2023-06-22 07:12 UTC
Labels: bug
