### ISSUE TITLE
The build failed. Fix the build errors and run again

### ISSUE THREAD

**Issue by burakakca** [grpc/grpc-dotnet#1908] opened 2022-10-11 12:14 UTC
```bash
git clone https://github.com/grpc/grpc-dotnet.git
cd grpc-dotnet/examples/Racer/Server
$ dotnet run
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/burak/Desktop/grpc/grpc-dotnet/examples/Racer/Server
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
Attempting to cancel the build...
^C
^C
^C

#Then when I run it again that command doesn't work.

$ dotnet run
The build failed. Fix the build errors and run again.
```

Linux Mint 20.2 Cinnamon

```bash
dotnet --info
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  3.1.423 [/usr/share/dotnet/sdk]
  7.0.100-rc.1.22431.12 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /home/burak/Desktop/grpc/grpc-dotnet/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by JamesNK** [comment] 2022-10-11 22:24
I can't reproduce this:

![image](https://user-images.githubusercontent.com/303201/195207646-f1e86303-a40a-4083-a474-cb35f8fa7ffe.png)

There is nothing unusual about that app. It's a standard Kestrel server. I'm not sure what could cause the build to fail. Your error message says the build failed because or errors. What are those errors? Is there a process in use?

**Comment by burakakca** [comment] 2022-10-12 07:36
I'm not using any third-party project. Just want to run those examples but when I run the racer example I'm getting that error. Before this, I was not getting such an error.

**Comment by JamesNK** [comment] 2022-10-17 04:51
I can't find out anymore if I don't have the build errors.

**Comment by burakakca** [comment] 2022-10-17 07:38
```
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
```
Actually, I didn't have any problem until running these examples. But it seems looks like the problem is .net SDK

 https://github.com/dotnet/sdk/issues/28471

**Comment by rafikiassumani-msft** [comment] 2022-10-18 22:59
Triage: Closing this issue as you believe it's an issue in the SDK.

**Closed by rafikiassumani-msft** 2022-10-18 22:59 UTC
Labels: bug, needs-author-feedback
