### ISSUE TITLE
Message Size Error while using Azure App Service

### ISSUE THREAD

**Issue by vivek306** [grpc/grpc-dotnet#1320] opened 2021-06-06 18:11 UTC
Status(StatusCode=\"Unavailable\", Detail=\"Error starting gRPC call. 
HttpRequestException: An error occurred while sending the request. 
IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.

had a similar error  a year back [here ](https://github.com/grpc/grpc-dotnet/issues/801) and it restarted again. All requested upto 100KB passes through and anything bigger than that ends up with the above error.

Client Code
```
                var httpClientHandler = new HttpClientHandler();
                var grpcWebHandler = new GrpcWebHandler(httpClientHandler);
                grpcChannel = GrpcChannel.ForAddress(url,
                    new GrpcChannelOptions
                    {
                        HttpHandler = grpcWebHandler
                    });
```

Server  (.net core 3.1)

Services

```
  services.AddGrpc(options =>
            {
                options.ResponseCompressionLevel = CompressionLevel.Optimal;
                options.ResponseCompressionAlgorithm = "gzip";
                options.EnableDetailedErrors = true;
                //options.MaxReceiveMessageSize = 4 * 1024 * 1024; // 4 MB
                //options.MaxSendMessageSize = 3 * 1024 * 1024; // 3 MB
            });

  services.AddGrpcHttpApi();

   services.AddGrpcReflection();
```

Configure

```
app.UseGrpcWeb();

app.UseEndpoints(endpoints =>
              {
                  endpoints.MapGrpcService<ConvertersService>().EnableGrpcWeb();
  
                  if (env.IsDevelopment())
                  {
                      endpoints.MapGrpcReflectionService();
                  }
              });
```

**Comment by vivek306** [comment] 2021-06-07 01:01
Error Log with stack trace for large files

Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStream.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslStream.HandleQueuedCallback(Object& queuedStateRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

**Comment by vivek306** [comment] 2021-06-07 12:48
After some more digging I feel [this ](https://stackoverflow.com/questions/47058434/web-api-in-azure-connection-setup-fails-with-large-requests) could be the real issue behind the above failure if Azure Windows is used as a host. 

Dont know how but hosting the same service in Azure Linux fixed it

**Comment by BrennanConroy** [comment] 2021-06-07 20:10
Root cause described at https://docs.microsoft.com/en-us/archive/blogs/waws/posting-a-large-file-can-fail-if-you-enable-client-certificates

Basically, the re-negotiate must either read the entire large request before sending the re-negotiate or in IIS's case fail the connection.

A possible hacky workaround is to do an initial "setup" request that is small and gets the re-negotiate out of the way, then doing the large request.

**Comment by vivek306** [comment] 2021-06-07 21:33
We are using cloudflare and the initial request hack doesnt seem to work probably becuase CN name doesnt match the custom domain name. Even tried adding the retrieved client certificate with a smaller message. 

```

                  var httpClientHandler = new HttpClientHandler();
                  httpClientHandler.ServerCertificateCustomValidationCallback = (requestMessage, certificate, certificateChain, policyError) =>
                  {
                      httpClientHandler.ClientCertificates.Add(certificate);
                      return policyError == SslPolicyErrors.None;
                  };

                  HttpClient client = new HttpClient(httpClientHandler);
                  var response = await client.GetAsync("CUSTOM DOMAIN GRPC URL");

```

Also tried adding ServicePointManager.Expect100Continue = true;

**Comment by vivek306** [comment] 2021-06-08 00:55
Tried using [client certificate](https://developers.cloudflare.com/ssl/client-certificates/create-a-client-certificate) generated in cloudflare 

                var clientCertificateFileName = @"PFX PATH";

                var clientCertificate = new X509Certificate2(clientCertificateFileName, "PFX PASSWORD");
                if (!clientCertificate.HasPrivateKey)
                    throw new ApplicationException("Cert doesn't contain private key");
                httpClientHandler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
                httpClientHandler.ClientCertificates.Add(clientCertificate);
                httpClientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
                httpClientHandler.CheckCertificateRevocationList = false;

doesnt seem to work either.

**Comment by Tratcher** [comment] 2021-06-09 20:52
> We are using cloudflare

So cloudflare terminating TLS and then forwarding that client cert as a header to app service?

In that case you'll need to set it to require a client cert at the start of connections. https://developers.cloudflare.com/ssl/client-certificates/enable-mtls

**Comment by vivek306** [comment] 2021-06-09 22:55
thank you for looking into this @Tratcher . 

Server - Azure App Service hosted in Windows
In the Cloudflare's SSL settings we got the origin certificates and binded it in the hosted grpc server for custom domain in azure.  

Client - Azure Functions
1) For the client initially tried the small request hack hoping for cloudflare to issue the required client certificate on the fly (not sure why this didnt work as  the issued certificates just worked to retrieve small data). We also got the Advanced certificate so the domain name should be there in the CN name.

2) We then generated the client certificates in this cloudflare settings, I did enable mTLS with the required domain and subdomains. httpclienthandler is setup with the client certificate at the start before a grpc and/or a http request is made.

All the above techniques lead to timeout error
{"Status(StatusCode=\"Unavailable\", Detail=\"Bad gRPC response. HTTP status code: 504\")"}

**Comment by Tratcher** [comment] 2021-06-12 02:13
Ultimately this needs to be resolved on cloudflare or app service, the client shouldn't need to do anything but pass in the certificate. You'll need help from them for that.

**Comment by vivek306** [comment] 2021-06-13 14:42
thanks, all works well if I have the client certificate mode set to "ignore" from App Service side. Will check will cloudflare n see what they say.

**Comment by JamesNK** [comment] 2021-06-15 07:55
Closing as this isn't an issue in grpc-dotnet.

**Closed by JamesNK** 2021-06-15 07:55 UTC
Labels: question
