### ISSUE TITLE
NotSupportedException: 'Cancellation of stream writes is not supported by this gRPC implementation.'

### ISSUE THREAD

**Issue by max-ieremenko** [grpc/grpc-dotnet#1747] opened 2022-05-17 07:13 UTC
Grpc.Net 2.46.0, Grpc.Core 2.46.1

### Is your feature request related to a problem? Please describe.

As an API user, i want to know if IAsyncStreamWriter supports WriteAsync(message, CancellationToken).
I don't want to guess or to catch NotSupportedException thrown by the default implementation.

### Describe the solution you'd like

change the default implementation, remove NotSupportedException:

``` c#
public interface IAsyncStreamWriter<T>
{
    Task WriteAsync(T message, CancellationToken cancellationToken) => WriteAsync(message);
}
```

### Describe alternatives you've considered

add indicator whether the current AsyncStreamWriter supports WriteAsync(message, CancellationToken)

``` c#
public interface IAsyncStreamWriter<T>
{
    bool CanCancelWriteAsync => false; // default false;

    Task WriteAsync(T message, CancellationToken cancellationToken)
    {
        if (cancellationToken.CanBeCanceled && !CanCancelWriteAsync)
        {
            throw new NotSupportedException("Cancellation of stream writes is not supported by this gRPC implementation.");
        }

        return WriteAsync(message);
    }
}
```

### Additional context

Few examples of WriteAsync in context of Grpc.Net and Grpc.Core [WriteAsyncChallenge.zip](https://github.com/grpc/grpc-dotnet/files/8705980/WriteAsyncChallenge.zip).

**Comment by JamesNK** [comment] 2022-05-24 04:09
Grpc.Core doesn't support `WriteAsync(message, CancellationToken)`. Grpc.AspNetCore does.

**Comment by JamesNK** [comment] 2022-05-24 10:56
> ### Describe alternatives you've considered
> add indicator whether the current AsyncStreamWriter supports WriteAsync(message, CancellationToken)\

That means the cancellation token would silently be ignored which isn't good.

**Comment by max-ieremenko** [comment] 2022-05-24 16:35
> Grpc.Core doesn't support `WriteAsync(message, CancellationToken)`. Grpc.AspNetCore does.

IAsyncStreamWriter.WriteAsync(CancellationToken) is defined in Grpc.Core is visible to developers and code analyzer.
Resharper makes a suggestion "hey, there's an overload with CancellationToken".


> > ### Describe alternatives you've considered
> > add indicator whether the current AsyncStreamWriter supports WriteAsync(message, CancellationToken)\
> 
> That means the cancellation token would silently be ignored which isn't good.

Forcing the user to catch "NotSupportedException" is not good either. What about the alternative "bool CanCancelWriteAsync"?

**Comment by JamesNK** [comment] 2022-05-31 22:15
Thank you for your feedback. We're closing this issue as the behavior discussed is by design.

**Closed by JamesNK** 2022-05-31 22:15 UTC
Labels: enhancement

**Comment by Falco20019** [comment] 2022-06-20 16:03
This sadly also did bite us... ReSharper is creating warnings that there is a variant with cancellation token support. Our users just applied it (as it's usually useful) and found out later that this is throwing an exception. So I'm also not too happy with the solution.

**Comment by NorekZ** [comment] 2024-06-10 09:52
I’d personally be fine with the current state if ReSharper isn’t suggesting filling in the cancellation token from context.

What about adding a setting that would suppress the exception? It’s unwatchable that no team member always ignores the suggestion.

**Comment by NorekZ** [comment] 2024-06-10 11:34
Thanks for suggestion.

I now realized this issue is for deprecated Grpc.Core.

We use Grpc.AspNetCore, where is the same problem.
