### ISSUE TITLE
Remove mandatory usage of exception

### ISSUE THREAD

**Issue by ziaulhasanhamim** [grpc/grpc-dotnet#1764] opened 2022-06-06 12:23 UTC
One of the biggest reasons behind Asp.Net Core's massive success is the performance. Exceptions are something that decreases performance pretty badly. Dotnet Grpc really makes it mandatory for you to throw exceptions for things(returning failure response from the server, getting failure response in client) that can be handled without exceptions even better without exceptions. Even just one (exception + try/catch) can show a notable req/sec decrease. **And it is not just about performance**. Exceptions are not considered good for control flow. It breaks the normal flow of a program. I see exceptions as a **fancy version of goto statements**. It's well-proven that exceptions aren't a good candidate for controlling the flow of the program. Also, exceptions make asynchronous programming difficult. Inconsistent state is another problem with an exception. It always leaves a possibility that the flow of the program can go backward from any line/method call. That's why you will see most modern languages don't even provide a feature for exception handling. Because exceptions are really the worst of both worlds.

**Comment by rafikiassumani-msft** [comment] 2022-06-07 22:28
@ziaulhasanhamim Triage: Can you provide a sample app with examples where you are forced to throw exceptions as well as benchmarks proving that these exceptions decrease performance?

**Comment by JamesNK** [comment] 2022-06-08 01:09
Isn't this a duplicate of https://github.com/grpc/grpc-dotnet/issues/1555?

**Comment by ziaulhasanhamim** [comment] 2022-06-08 02:25
@rafikiassumani-msft these are situations where I'm forced to throw or catch #1538 #1555. I will provide the benchmark as soon as possible.
@JamesNK Yeah related but not duplicate

**Comment by JamesNK** [comment] 2022-06-22 01:53
The way to do this on the client is to have a method that waits for the response (or failure) from a unary call, and the check status. Unless we rewrite the internals of gRPC client an exception is probably still being thrown internally. It won't make a difference to performance.

If more people request this then we can consider it.

In your own app you could write a helper method that allows you to wait for a response and then check the status code without seeing an exception.

**Closed by JamesNK** 2022-06-22 01:53 UTC
Labels: enhancement, needs-author-feedback

**Comment by JamesNK** [comment] 2022-06-22 01:55
> In your own app you could write a helper method that allows you to wait for a response and then check the status code without seeing an exception.

I already showed how to do this in a previous issue: https://github.com/grpc/grpc-dotnet/issues/1538

Please stop recreating the same issue. It's not a good use of anyone's time.

**Comment by ziaulhasanhamim** [comment] 2022-06-22 02:34
What about the server?

**Comment by ziaulhasanhamim** [comment] 2022-06-22 02:36
> If more people request this then we can consider it.

Then keep the issue open

**Comment by JamesNK** [comment] 2022-06-22 02:55
Server has been discussed in other issues...

We don't leave these kinds of issues open. People commenting or upvoting in closed issues counts as feedback. Or opening new issues. If demand is shown then it will be reopened.

**Comment by ziaulhasanhamim** [comment] 2022-08-11 17:59
@JamesNK have you checked benchmark repo I provided there?
