### ISSUE TITLE
HTTP3 QUIC - client over Cronet sends CertificateUnknown and closes QUIC listener

### ISSUE THREAD

**Issue by ValeryYegorov** [grpc/grpc-dotnet#1956] opened 2022-11-21 17:13 UTC
### What version of gRPC and what language are you using?
Server - Grpc.AspNetCore.Server 2.49.0 (C#)
Client - Android Cronet

### What operating system (Linux, Windows,...) and version?
On Windows Version	10.0.20348 Build 20348 - All works Ok
On Amazon Linux release 2 (Karoo) - have a BUG

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Server:
 - VS 2022 17.4.0
 - .NET SDK 7.0.100
 
Client:
 - io.grpc:grpc-cronet:1.49.0
 - com.google.android.gms:play-services-cronet:18.0.1

### What did you do?
I'm implementing gRPC QUIC for bidirectional client-server interaction. SSL connection creates using letsencrypt certificate. Server side on linux. Client side on Android/IoS. When I connect to gRPC server over linux using WinForms application - all Ok. When I connect using Android/Cronet -  client after connection sends 'CertificateUnknown' and it terminate QUIC listener.

### What did you expect to see?
WinForm, Android and IoS client can interact with server using bidirectional streams. If any exception or failure gRPC QUIC listener should continue or restart.

### What did you see instead?
WinForms - all Ok. Android client after connection sends CertificateUnknown and it terminate QUIC listener.

### Anything else we should know about your project / environment?
Client and server logs attached in logs.zip
To read Cronet logs (netlog_21_11_1.json) you can use https://netlog-viewer.appspot.com/#events
logs-insights-results.json - server logs

[logs.zip](https://github.com/grpc/grpc-dotnet/files/10058563/logs.zip)

**Comment by ValeryYegorov** [comment] 2022-11-22 19:44
I checked 
`openssl s_client -showcerts -connect grpctest.mydomain.mydomain.com:1189`
```
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.mydomain.mydomain.com
verify return:1
---
Certificate chain
 0 s:/CN=*.mydomain.mydomain.com
   i:/C=US/O=Let's Encrypt/CN=R3
-----BEGIN CERTIFICATE-----
MIIEnjCCA4agAwIBAgISBJkTrYyDY9oDZIQ7/v2HZ6VRMA0GCSqGSIb3DQEBCwUA
...
MRTp9UwKZF9KKny2MhkSAdlXHB13xZtZy/+dTdkZSiIe0mgh2bRMHHwi2uCzRsQw
8sJmsDjgQYOIpQxk3kzhU+KoP8zF/pu6efLhL4p+Up5M9g==
-----END CERTIFICATE-----
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/C=US/O=Internet Security Research Group/CN=ISRG Root X1
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
...
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=*. mydomain.mydomain.com
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 2858 bytes and written 447 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 384 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: 9A03000084FAD6BEB5C944C1BB5958A77BE8E0714E0B6184B80BFF3D58DB5E85
    Session-ID-ctx:
    Master-Key: E726262FC35627BE83A223739146468319D3D4CF38F0BB6B9E3E0352BA865FDC9E2BEB1C43DD79B85F42F706C7A8666E
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1669144119
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
password
HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Date: Tue, 22 Nov 2022 19:08:43 GMT
Server: Kestrel
Alt-Svc: h3=":1189"; ma=86400
```

Shows 2 certificates. But in Cronet logs I see 1 certificate without intermediate.
After client attempt I have following exception on server:
`
Microsoft.AspNetCore.Server.Kestrel[0] The connection listener failed to accept any new connections. System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'CertificateUnknown'.    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) --- End of stack trace from previous location ---    at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.Quic.QuicListener.PendingConnection.StartHandshake(QuicConnection connection, SslClientHelloInfo clientHello, Func`4 connectionOptionsCallback)    at System.Net.Quic.QuicListener.PendingConnection.DisposeAsync()    at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.AcceptAsync(IFeatureCollection features, CancellationToken cancellationToken)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher``1.<>c__DisplayClass8_0.<<StartAcceptingConnectionsCore>g__AcceptConnectionsAsync|0>d.MoveNext()`

**Comment by JamesNK** [comment] 2022-11-23 23:17
@nibanks Do you know what is going on here? What would cause an `CertificateUnknown` error?

**Comment by nibanks** [comment] 2022-11-24 00:20
We'd need logs to diagnose further, but I think LTTng doesn't work on Android.

**Comment by ValeryYegorov** [comment] 2022-11-25 20:59
Hi @nibanks.

We did upgrade dotnet from RC2 to 7.0 release.
With this setup Android client does connect to GRPC over QUIC, with an exception. Client needs to make two conseceutive connection requests.

First connect attempt fails with "CertificateUnknown" and next request goes through.
To check Android log you can use following:
That is successfully Cronet log to linux server. [netlog_25_11_success.log](https://github.com/grpc/grpc-dotnet/files/10095019/netlog_25_11_success.log)
That is unsuccesfull Cronet log to linux server. [netlog_25_11_failed.log](https://github.com/grpc/grpc-dotnet/files/10095024/netlog_25_11_failed.log)
[Cronet log viewer](https://netlog-viewer.appspot.com/#events)

If you need, I  can provide any additional server log. 

Best regards.
Valery

**Comment by nibanks** [comment] 2022-11-25 21:05
> First connect attempt fails with "CertificateUnknown" and next request goes through.

Is the second request going over a TCP/H2 connection or a QUIC/H3 connection?

Does QUIC work if you disable server certificate validation?

**Comment by ValeryYegorov** [comment] 2022-11-27 15:39
Hi @nibanks 
After dotnet version upgrade we still have  "CertificateUnknown" exception. 
But listener is still on and on second try client connects successfully over HTTP3.
1) All requests going over QUIC/H3
2) If you mean 
`
ServicePointManager.ServerCertificateValidationCallback +=
                (sender, cert, chain, sslPolicyErrors) => true;
`
I tried that fix, but nothing change.

Please suggest how to fix first attempt.

**Comment by ValeryYegorov** [comment] 2022-11-29 18:07
Hi @nibanks, @JamesNK  
We tested QUIC/H3 over IoS and saw different server  behavior between Linux and Windows running same gRPC application:
**On linux server - 'CertificateUnknown'**
via TLS - server sends 2 certificates leaf and intermediate.
via QUIC  - server sends only 1 leaf certificate without intermediate. You can look at cronet logs above. 
Additionally you can check tcpdump below.
[tcpdump_ios_client1.zip](https://github.com/grpc/grpc-dotnet/files/10115360/tcpdump_ios_client1.zip)
![linux_server](https://user-images.githubusercontent.com/61559097/204606528-f470258b-4879-48b2-82fc-5e50db5430d0.png)
**On windows server - OK** 
via TLS - server sends 2 certificates leaf and intermediate
via QUIC - server sends 2 certificates leaf and intermediate
[tcpdump_windows_server.zip](https://github.com/grpc/grpc-dotnet/files/10115807/tcpdump_windows_server.zip)
![windows_server](https://user-images.githubusercontent.com/61559097/204606827-23413bcf-ac7f-4448-9b87-78193b87150c.png)

Best regards
Valery.

**Comment by gradx** [comment] 2022-12-09 19:34
Can @JamesNK confirm .NET 7 supports GRPC over http/3?  Whenever I restrict the service to http3 it fails for both Windows and Linux, and according to this article only http/2 is supported 

https://learn.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-7.0

**Comment by ValeryYegorov** [comment] 2022-12-09 21:41
Hi @gradx . It works for windows without any issues.
@JamesNK , @nibanks For test purposes I created new gRPC application from VisualStudio gRPC template. Modifed appsettings by adding port and fullchain certificate
```
"Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http1AndHttp2AndHttp3"
    },
    "Endpoints": {
      "Https": {
        "Url": "https://*:1191"
      }
    },
    "Certificates": {
      "Default": {
        "Path": "fullchain.pem",
        "KeyPath": "private.key"
      }
    }
  }
```
As cilent-side we use Android/Cronet (same as earlier). 
gRPC started on Windows - all works correctly.
gRPC started on linux (Amazon and Debian)  - same as earlier. On client application start,  server sends only 1 leaf certificate

[netlog_09_12_1.zip](https://github.com/dotnet/runtime/files/10198226/netlog_09_12_1.zip)
[client_log_viewer](https://netlog-viewer.appspot.com/#events)

Best regards.

**Comment by gradx** [comment] 2022-12-10 06:16
@ValeryYegorov from my testing with the Http1AndHttp2AndHttp3 setting on Windows, Wireshark shows it uses TCP and not UDP and according to the article below it's not yet supported even though it has some sample example code provided to show how "simple" it would be:

https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/#grpc-with-http-3

And reading through the article I found the gRPC over http/3 proposal which was never closed:

https://github.com/grpc/proposal/pull/256

**Comment by amcasey** [comment] 2022-12-12 23:18
Triage: @JamesNK to comment/clarify

**Comment by JamesNK** [comment] 2022-12-13 00:10
Even when a server supports HTTP/3, the first request typically uses HTTP/2, the response gives metadata to the client that allows it to upgrade to HTTP/3.

**Comment by gradx** [comment] 2022-12-14 05:48
> Even when a server supports HTTP/3, the first request typically uses HTTP/2, the response gives metadata to the client that allows it to upgrade to HTTP/3.

Thank You @JamesNK 

I was able to confirm gRPC over HTTP/3 using the Http1Http2Http3 setting but only after establishing an HTTP/3 connection to a REST endpoint using the .NET HttpClient

**Comment by gradx** [comment] 2022-12-19 17:39
@JamesNK Performing the same test on Linux with the Debian 11 docker image I do receive similar behavior as @ValeryYegorov using the .NET http client

dotnet: Version: 7.0.100
libmsquic: Version: 2.1.4

Using  the **Http1AndHttp2AndHttp3** and a self-signed certificate with the .NET HttpClient from the same instance:

Successful:
DefaultRequestVersion = HttpVersion.Version20,
DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher

Failure:             
DefaultRequestVersion = HttpVersion.Version30,
DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher

**The first request returns: Unhandled exception. System.Net.Http.HttpRequestException: The request was aborted.**

Unhandled exception. System.Net.Http.HttpRequestException: The request was aborted.
   at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

**Second Request: System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'BadCertificate**'.

Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'BadCertificate'.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken)
   at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

**Comment by gradx** [comment] 2022-12-29 09:23
@JamesNK I've created an end-to-end Docker-based unit test to show the behavior of  .NET 7 Http on Linux Kestrel that will create and install the necessary certificates since I believe the issue may be somewhere in the SSL configuration.

Http2 Self-Signed: Success
Http2 Chained: Success

Http3 Self-Signed: Failure
Http3 Chained: Failure

https://github.com/gradx/GrpcHttp3Net70Example

**Comment by gradx** [comment] 2022-12-30 07:48
Some good news @JamesNK and @ValeryYegorov! It appears the [AllowAnyClientCertificate ](https://github.com/gradx/GrpcHttp3Net70Example/blob/main/GrpcService/Program.cs#L16)option for Kestrel is required when using Http3.  

I've now updated my unit tests to add gRPC + Http3 which now pass

**Comment by gradx** [comment] 2022-12-31 22:43
I've done a little more digging on the Bad Certificate issue and the logs show it was related to a **RemoteCertificateNameMismatch** so I used ClientCertificateValidation  to override the error and continue.

This appears to work for all unit tests except  gRPC with an Http3 only configuration.

        options.ClientCertificateValidation = (certificate2, chain, policyErrors) =>
        {
            Console.WriteLine("Cert Chain: " + chain?.ChainElements.FirstOrDefault()?.Certificate?.Subject);
            if (policyErrors == SslPolicyErrors.RemoteCertificateNameMismatch && (certificate2.Subject.StartsWith("CN=mydomain.com") 
                || certificate2.Subject.StartsWith("CN=chained.mydomain.com")))
                policyErrors = SslPolicyErrors.None;

            if (policyErrors != SslPolicyErrors.None)
            {
                Console.WriteLine("Certificate PolicyErrors: " + policyErrors + " for " + certificate2.Subject);
                return false;
            }
            else
            {
                //Console.WriteLine("Certificate PolicyErrors: " + policyErrors + " for " + certificate2.Subject);
                return true;
            }
        };

**Comment by JamesNK** [comment] 2023-03-27 13:05
It looks like this has been figured out. Let me know if I can close it.

**Closed** 2023-04-05 01:25 UTC
Labels: bug

**Comment by abdullahaygun** [comment] 2023-11-24 14:24
> gRPC + Http3


How did you pass to do this? I added AllowAnyClientCertificate() as you said, but the result did not change. In short, is the error caused by the certificate?
