### ISSUE TITLE
ClientFactory .Net Core 3.0 Support

### ISSUE THREAD

**Issue by efeozyer** [grpc/grpc-dotnet#478] opened 2019-08-08 12:59 UTC
*grpc-aspnetcore* 

 Example.Order.ServiceHost.csproj: [NU1202] Package Grpc.Net.ClientFactory 0.1.22-pre2 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Grpc.Net.ClientFactory 0.1.22-pre2 supports: netstandard2.1 (.NETStandard,Version=v2.1)

Could you push Grpc.Net.ClientFactory package with .Net Core 3.0 support?

**Comment by jtattermusch** [comment] 2019-08-27 10:11
Closing as "cannot reproduce".

**Closed by jtattermusch** 2019-08-27 10:11 UTC

**Comment by GeirGrusom** [comment] 2020-05-06 08:35
I was getting this as well

> NU1202: Package Grpc.Net.ClientFactory 2.28.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1).
> Package Grpc.Net.ClientFactory 2.28.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)
>    NU1202: Package Grpc.Net.Common 2.28.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package
> Grpc.Net.Common 2.28.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)

In my case it was an issue caused by using an old version of NuGet and not related to this library.
