### ISSUE TITLE
Difference between server and client RpcException

### ISSUE THREAD

**Issue by xolott** [grpc/grpc-dotnet#152] opened 2019-03-09 06:47 UTC
I'm trying to add custom data to the RpcException generated by my server. Like this:

```csharp
throw new RpcException(
    status: new Status(StatusCode.InvalidArgument, "Custom details"),
    trailers: new Metadata(),
    message: "CustomInvalidArgumentException"
);
```

But, on the client side, I keep getting this exception:

```
Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")
         at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 61
```

I changed the `StatusCode` to `Unknown` and the client shows the correct exception information. Is there any reason that justifies the  `Cancelled` status?

Using Grpc.Core 1.17.0

**Comment by JamesNK** [comment] 2019-03-10 18:39
If you throw an RpcException on the server then Grpc.AspNetCore.Server it will return the exception's status to the client. I think the problem is the client is throwing an exception with the cancelled status. Thoughts @jtattermusch?

**Comment by jtattermusch** [comment] 2019-03-11 18:56
@xolott   I saw that you also posted the same issue as https://github.com/grpc/grpc/issues/18316 - that one was closed as not reproducible.  It looks like you are using Grpc.Core and not Grpc.AspNetCore.Server (which lives in this repository), so I'm going to close this issue as well. Happy to reopen once we have a working reproduction.

**Closed by jtattermusch** 2019-03-11 18:56 UTC

**Comment by xolott** [comment] 2019-03-11 19:38
I was not sure where to post this. I will upload a reproducible code as soon as possible.
Grpc.AspNetCore.Server is the recommended way to develop grpc services? I'm coming from python so I tried to follow similar steps while writting the server :cry: 

That's why I use Grpc.Core

**Comment by xolott** [comment] 2019-03-11 20:46
I managed to find where the issue is originated. I'm trying to return the internal Stack Trace of my custom exception via Metadata.

I implemented the Greeter Example using Grpc.Core, and modified the `SayHello` method

```csharp
public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
{
    try
    {
        RecursiveMethod(4);
    }
    catch(Exception)
    {
        var metadata = new Metadata();
        metadata.Add("stack_trace", exc.StackTrace);
        throw new RpcException(
            status: new Status(StatusCode.InvalidArgument, "Custom details"),
            trailers: metadata,
            message: "Custom Message"
        );
    }
}
private void RecursiveMethod(int iteration)
{
    if(iteration < 1)
    {
        throw new Exception("Custom Exception!");
    }
    RecursiveMethod(iteration -1);
}
```
This exception generate the following stack trace (722 chars length):

```
at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.RecursiveMethod(Int32 iteration) in ~/Desktop/app/Services/GreeterImpl.cs:line 45
   at Greeter.Service.GreeterImpl.SayHello(HelloRequest request, ServerCallContext context) in ~/Desktop/app/Services/GreeterImpl.cs:line 51
```

And receive a `Cancelled` status on the client side. If I set to 0 the parameter passed to `RecursiveMethod` (reducing the length of the stack trace), o remove the metadata from the generated `RpcEception`, the client receives the custom RpcException.

Is there any limitation on the metadata?

**Comment by xolott** [comment] 2019-03-11 21:21
I just notice that this repository is an early development. Sorry for that, I will continue my issue on the other thread grpc/grpc#18316
